<?php

/**
 * Implements hook_menu().
 */
function airs_xacml_menu() {
  $items = array();

  $items['airs-xacml/realname/autocomplete'] = array(
    'title' => 'Airs Real user Auto Complete',
    'description' => 'Autocomplete for airs.',
    'page callback' => 'airs_xacml_autocomplete',
    'type' => MENU_CALLBACK,
    'access arguments' => array('access content'),
    'page arguments' => array(3),
  );

  return $items;
}

function airs_xacml_autocomplete($string) {
  $matches = array();
  //debug($string, TRUE);
  $query = db_select('realname', 'rn');
  $query->fields('rn', array('realname'));
  $query->condition('rn.realname', db_like($string) . '%', 'LIKE');
  $real_names = $query->execute()->fetchCol();
  foreach ($real_names as $real_name) {
    $matches[$real_name] = $real_name;
  }
  drupal_json_output($matches);
}


/**
 * Implements hook_islandora_object_ingested
 */
function airs_xacml_islandora_object_ingested($object) {
  if ($object->models[0] != 'ir:citationCModel' && !empty($object['MODS'])) {
    $xmlPath = drupal_get_path('module', 'airs_xacml');
    $mods = new SimpleXMLElement($object['MODS']->getContent(''));
    $dsid = 'POLICY';
    $datastream2 = isset($object[$dsid]) ? $object[$dsid] : $object->constructDatastream($dsid);
    $datastream2->label = 'XACML Policy Stream';
    $datastream2->mimeType = 'text/xml';
    $datastream2->setContentFromFile($xmlPath.'/XACML Policy Stream.xml');
    $object->ingestDatastream($datastream2);
    $object->refresh();
    airs_xacml_apply_policy($mods, $object);
  }
}

/**
 * Implements hook_islandora_datastream_modified
 */

function airs_xacml_islandora_datastream_modified($object, $datastream) {
  if ($object->models[0] != 'ir:citationCModel') {
    $xmlPath = drupal_get_path('module', 'airs_xacml');
    if ($datastream->label === 'MODS Record') { 
      $mods = new SimpleXMLElement($object['MODS']->getContent(''));
      $dsid = 'POLICY';
      $datastream2 = isset($object[$dsid]) ? $object[$dsid] : $object->constructDatastream($dsid);
      $datastream2->label = 'XACML Policy Stream';
      $datastream2->mimeType = 'text/xml';
      $datastream2->setContentFromFile($xmlPath.'/XACML Policy Stream.xml');
      $object->ingestDatastream($datastream2);
      $object->refresh();
      airs_xacml_apply_policy($mods, $object);
    }
  }
}

function airs_xacml_apply_policy($mods, $object) {
  // DECLARATIONS
  global $user;
  $sub_theme = 'Subtheme';

  $userAccess = userAccess_declaration($mods, $object);
  $contributors = contributors_declaration($mods, $object);
  $themes = themes_declaration($mods, $object);

  // create new IslandoraXacml object, link it to the object being ingested
  $xacml = new IslandoraXacml($object);

  // allow the user to view and manage the file
  // the administrative role gets this by default
  $xacml->viewingRule->addUser(array($object->owner, 'admin'));
  $xacml->managementRule->addUser(array($object->owner, 'admin')); 

  if ($userAccess != 'User only') {
    // grabs all users listed as collaborators
    foreach ($contributors as $name) {
      $xacml->viewingRule->addUser(array($name));
      $xacml->managementRule->addUser(array($name));
    }

    // use the userAccess field of the form to determine extra permissions
    switch($userAccess) {
      case 'Public':
        $xacml->viewingRule->addRole(array('anonymous user', 'authenticated user'));
        $xacml->viewingRule->addUser(array('anonymous'));
        if (airs_xacml_is_collection($object)) {
          $xacml->managementRule->addRole(array('Member'));
        }
        break;

      case 'Registered users':
        $xacml->viewingRule->addRole(array('authenticated user'));
        if (airs_xacml_is_collection($object)) {
          $xacml->managementRule->addRole(array('Member'));
        }
        break;

      case 'My sub-theme':
        // returns all themes listed in the AIRS Themes field
        foreach ($themes as $theme) {
          // checks if the listing is a string, then if contains Subtheme
          if (is_string($theme) && strlen($theme) > 5) {
            if (substr($theme, 0, 8) == 'Subtheme') {
              $subthemeID = 'st'.substr($theme, 9, 3);
              $xacml->viewingRule->addRole(array($subthemeID));
              $xacml->managementRule->addRole(array($subthemeID));
            }
          } 
        }
      break;
    }
  }
  // save the policy
  $xacml->writeBackToFedora();
}

// designed to declare a $userAccess var
function userAccess_declaration($mods, $object) {
  foreach ($mods->accessCondition as $access) {
    switch((string) $access['type']) {
    case 'restriction on access':
      $userAccess = (string)$access;
      break;
    }
  }
  return $userAccess;
}

// designed to declare a $contributors array
function contributors_declaration($mods, $object) {
  $n=0;
  foreach ($mods->name as $name) {
    switch((string) $name['type']) {
    case 'personal':
      foreach($name->namePart as $namePart) {
        // lookup the username based on the realname that is stored in the mods.
        $username = airs_xacml_get_username((string)$namePart);
        if(empty($username)){
          $username = (string)$namePart;
        }
        $contributors[$n] = $username;
        $n++;
      }
      break;
    }
  }
  return $contributors;
}

/**
 * Gets the username from the drupal database based on the realname.
 * @param string $realname
 *   a realname may look like Annabel J. Cohen
 * @return mixed
 *   a drupal user name (may look like acohen) or NULL if no match
 */
function airs_xacml_get_username($realname){
  // Assuming realnames must be unique for each drupal
  $query = db_select('realname', 'rn');
  $query->fields('rn', array('uid'));
  $query->condition('rn.realname', $realname);
  $rids = $query->execute()->fetchCol();
  if(!empty($rids)) {
    $real_user = user_load($rids[0]);
    return $real_user->name;
  }
}

// designed to declare $themes
function themes_declaration($mods, $object) {
  $t=0;
  foreach ($mods->genre as $genre) {
    switch((string) $genre['type']) {
    case 'themes':
      $themes[$t] = (string)$genre;
      $t++;
      break;
    }
  }
  return $themes;
}

function airs_xacml_is_collection($object) {
  if (strcmp($object->models[0], 'islandora:collectionCModel') == 0) {
    return true;
  } else {
    return false;
  }
}

// implements hook_islandora_form_alter
/*function airs_xacml_form_alter(&$form, &$form_state, &$form_id) {
  //dpm($form_id); // displays name of forms on the page
  //dpm($form); // displays form information
} */
